version: "3"
services:
  neo4j:
    image: neo4j:5.6
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test1234
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.export.*"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_directories_import: "/import"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./import:/import  # Maps to a local directory on macOS for exports
      - ./plugins:/plugins  # Plugins directory
volumes:
  neo4j_data:
  neo4j_logs:
